global:
  owner: quickstart-eng@amazon.com
  qsname: quickstart-docker
  marketplace-ami: false
  reporting: true
  regions:
    - us-east-1
    - us-west-1
    - eu-west-1
    - us-west-2
    - eu-central-1
    - ap-southeast-1
    - ap-southeast-2
tests:
  docker:
    template_file: quickstart-docker.template
    parameter_input: quickstart-docker.json 
